# Generated by Django 2.2.4 on 2019-10-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20191002_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manufacture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='modelseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'models',
                'managed': False,
            },
        ),
    ]
