# Generated by Django 2.2.4 on 2019-10-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_manufactures_modelseries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manufactures',
        ),
        migrations.DeleteModel(
            name='modelseries',
        ),
    ]
